name: Run benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'benchmarks/**.py'
      - 'src/**.py'
      - setup.cfg
      - .github/workflows/benchmarks.yml
      - requirements-test.txt

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", pypy-3.8]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    # Service containers to run with `container-job`

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run benchmarks
      run: |
        pytest benchmarks/  --benchmark-json output.json
    - name: Analyse benchmark results for Pull Requests
      uses: rhysd/github-action-benchmark@v1.13.0
      if: ${{ github.ref != 'refs/heads/master' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
    - name: Store benchmark result for master branch
      uses: rhysd/github-action-benchmark@v1.13.0
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
#        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
#        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
